name: release
on:
  push:
    branches:
    - main
jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.tag.outputs.changelog }}
      tag: ${{ steps.tag.outputs.new_tag }}
      version: ${{ steps.tag.outputs.new_version }}
      date: ${{ steps.date.outputs.date }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Save the date
      id: date
      run: |
        echo ::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - name: Bump version and tag
      uses: mathieudutour/github-tag-action@v6.1
      id: tag
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  binaries:
    name: build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: WillAbides/setup-go-faster@v1.14.0
      with:
        go-version: '1.24'
    - name: Build
      run: |
        GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} go build -o chargeflux-${{matrix.goos}}-${{matrix.goarch}} -v
    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: chargeflux-${{matrix.goos}}-${{matrix.goarch}}
        path: chargeflux-${{matrix.goos}}-${{matrix.goarch}}
        retention-days: 1

  container:
    name: build container
    runs-on: ubuntu-latest
    needs: tag
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push containers
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository }}:${{ needs.tag.outputs.tag }}
        labels: |
          org.opencontainers.image.title=${{ github.event.repository.name }}
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.created=${{ needs.tag.outputs.date }}
          org.opencontainers.image.version=${{ needs.tag.outputs.tag }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

  release:
    needs:
    - tag
    - container
    - binaries
    runs-on: ubuntu-latest
    steps:
    - name: Restore artifact
      uses: actions/download-artifact@v4
      with:
        pattern: chargeflux-*-*
        merge-multiple: true
        path: release
    - name: Create checksums
      run: |
        sha256sum release/chargeflux-* | tee release/chargeflux.sha256
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        name: Release ${{ needs.tag.outputs.version }}
        body: |
          Changes in this release:

          ${{ needs.tag.outputs.changelog }}

          Docker image: `ghcr.io/${{ github.repository }}:${{ needs.tag.outputs.tag }}`
        files: release/*
